### ISSUE TITLE
Submitting Ruby Tempfiles

### ISSUE THREAD

**Issue by wbcasey** [onfido/onfido-ruby#10]
When submitting Tempfile object as the `file` parameter to the document submissions endpoint we get back a 422. The error is "Attachment is invalid, Attachment content-type is invalid". This is really interesting since Tempfile objects meet the API documentation's requirements specified of "must respond to #path and #read".

**Comment by ciaran16** [comment]
Hi @wbcasey, I think it gets the content type from the file extension in the path. Could you check the TempFile has the correct file extension for the image it represents? e.g `Tempfile.new(['file', '.jpg'])`

If you're still having an issue could you open a support ticket by emailing client-support@onfido.com?

**Comment by wbcasey** [comment]
@ciaran16 I tried setting that explicitly as well, but no dice.

**Comment by ciaran16** [comment]
Hi @wbcasey, I managed to get this working:

```rb
applicant_id = ...
data = ...

temp_file = Tempfile.new(['file', '.png'])
temp_file.write(data)
temp_file.rewind

document = onfido.document.create({
  applicant_id: applicant_id,
  type: "passport",
  file: temp_file
})

temp_file.close
temp_file.unlink
```

If you're still having an issue, it could be something to do with the data you're writing to the `Tempfile`. I recommend you email api@onfido.com, who will be able to provide you with quicker support than me.

**Comment by wbcasey** [comment]
@ciaran16 what extensions do you accept for files? Maybe that is where the problem is.

**Comment by wbcasey** [comment]
This did the trick! We can now use tempfiles! Thank you
